baseurl = "http://www.manuellecha.com"
title = "Manuel Lecha"
theme = "hugo-coder."
languagecode = "en"
defaultcontentlanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
katex = true
custom_css = ["css/custom.css"]
extra_head = "extra_head.html"
author = "Manuel Lecha"
info = ["PhD Student at University of Barcelona"]
keywords = "personal, Mathematics, Computer Science"
avatarURL = "roundme.png"
description = "Hi! My name is Manuel Lecha and I am from Barcelona, Spain. I am a Mathematics and Computer Science graduate. Welcome to my personal webpage!"
#gravatar = "mlechasanchez@gmail.com"
showcredit = false
since = 2023
colorScheme = "auto"
hideColorSchemeToggle = true


[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Gmail"
icon = "fa fa-2x fa-envelope"
weight = 1
url = "mailto:mlechasanchez@gmail.com"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 2
url = "https://www.linkedin.com/in/manuellecha/"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 3
url = "https://github.com/manuellecha/"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 4
url = "https://twitter.com/manuel_lecha"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Materials"
weight = 3
url = "materials/"

[markup.goldmark.renderer]
    unsafe = true

