baseurl = "http://www.manuellecha.com"
title = "Manuel Lecha"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "Manuel Lecha"
info = ["Mathematics & Computer Science"]
keywords = "personal, Mathematics, Computer Science"
avatarURL = "images/Logo.png"
description = ""
#gravatar = "mlechasanchez@gmail.com"
showcredit = false
since = 2022
colorScheme = "auto"
hideColorSchemeToggle = false

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Gmail"
icon = "fa fa-2x fa-envelope"
weight = 1
url = "mailto:mlechasanchez@gmail.com"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 2
url = "https://www.linkedin.com/in/manuellecha/"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 3
url = "https://github.com/manuellecha/"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 4
url = "https://twitter.com/manuel_lecha"


[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

